# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dbf7a93d378e25f91d693aaf2d5c3f8251d6605be3e869dbde5cb138049e52aac52e47f6353b1a1d4933038f90ac9d4a97911969d86ff5e144731627e680cb8

test:
  secret_key_base: 938d355f5fe47b216a36ef91489e9e918a19d82d8be92ed49ea26aa0992d57b1798b9175117e4af8c0ff78d3e67957353502a2f233e25a5029c042f32096d2b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
